Fixed ECDH key to have keyAgreement in its KeyUsage extension
It seems that the latest X509Certificate2 impl validates that this key usage is set if the KeyUsage extension exists.

Unfortunately, this still isn't enough to fix CmsSignerTests.TestConstructors() which is now failing with:

System.Security.Cryptography.CryptographicException: Keyset does not exist
   at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider, CngKeyOpenOptions openOptions)
   at System.Security.Cryptography.X509Certificates.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
   at System.Security.Cryptography.X509Certificates.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at MimeKit.Cryptography.X509Certificate2Extensions.GetPrivateKeyAsAsymmetricKeyParameter(X509Certificate2 certificate) in C:\src\MimeKit\MimeKit\Cryptography\X509Certificate2Extensions.cs:line 249
   at MimeKit.Cryptography.CmsSigner..ctor(X509Certificate2 certificate, SubjectIdentifierType signerIdentifierType) in C:\src\MimeKit\MimeKit\Cryptography\CmsSigner.cs:line 347
   at UnitTests.Cryptography.CmsSignerTests.TestConstructors() in C:\src\MimeKit\UnitTests\Cryptography\CmsSignerTests.cs:line 155